try {
    throw Error('Esto es un mensaje de error')
  } catch(e){
    console.log(e)
  }
  

  
  